name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pre-commit
        python -m pip install --upgrade platformio
    - name: pre-commit
      run: |
        pre-commit run --all-files
    - name: Build PlatformIO Project
      run: pio run
    - name: Create timestamp for artifact
      run: echo "TODAY=$(date +'%Y%m%d')" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v3
      with:
        name: firmware-${{env.TODAY}}-git-${{github.sha}}.bin
        path: .pio/build/esp12e/firmware.bin
